config/routes.rb
Rails.application.routes.draw do
  resources :notes do
    collection do
      get :manage

      post :rebuild
      post :expand_node
    end
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  has_many :child_note_links, :class_name => 'NoteLink', :foreign_key => 'parent_id'
  has_many :children, :through => :child_note_links, :source => :child
  has_many :parent_note_links, :class_name => 'NoteLink'
  has_many :parents, :through => :parent_note_links, :source => :parent

  accepts_nested_attributes_for :child_note_links
  accepts_nested_attributes_for :parent_note_links
end

app/models/note_link.rb
class NoteLink < ActiveRecord::Base
  belongs_to :parent, :class_name => 'Note'
  belongs_to :child, :class_name => 'Note', :foreign_key => :note_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where(parent_id: nil)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new(xpos: params[:xpos], ypos: params[:ypos])
    render layout: false
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.create(note_params)
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:text, :xpos, :ypos, :width, :height, child_note_links_attributes: [ :parent_id, :position ], parent_note_links_attributes: [:parent_id, :position])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-new_note="<%= new_note_path %>">

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note, remote: true, :authenticity_token => true, html: { class: 'new_note', style: "padding-top: 12px; border-top: black solid 1px; position: absolute; top: #{params[:ypos]}px; left: #{params[:xpos]}px;"}) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :xpos %>
  <%= f.hidden_field :ypos %>
  <%= f.hidden_field :width %>
  <%= f.hidden_field :height %>
  <div class="field">
    <%= f.text_area :text %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div data-update-url="<%= note_path(note) %>" class="note" style="position:absolute;top: <%=note.ypos %>px; left: <%=note.xpos %>px;  border: black solid 1px; padding: 3px; width: <%=note.width %>px; height: <%=note.height %>px;">
  <div style="float:left"><%= best_in_place note, :text, :as => :textarea, :display_with => lambda { |v| simple_format(v, {}, wrapper_tag: 'div') } %></div>
  <div style="position: absolute;right: 0px;margin-top: -7px;"><%= link_to 'x', note, method: :delete, remote: true %></div>
  <%= content_tag('ol', class: 'sortable_tree expandable', data: { rebuild_url: rebuild_notes_url, expand_node_url: expand_node_notes_url } ) do
    expandable_tree note , {title: :text}
    end %>
</div>

app/views/notes/_static_form.html.erb
<%= form_for(@note, remote: true,:authenticity_token => true, html: { class: 'new-sub-note-form'}) do |f| %>
    <%= f.fields_for :parent_note_links, @note.parent_note_links.new do |g| %>
        <%= g.hidden_field :position, value: params[:position] %>
        <%= g.hidden_field :parent_id, value: params[:parent_id] %>
    <% end %>
    <div class="field">
      <%= f.text_area :text %>
    </div>
<% end %>

app/views/notes/_sub_note.html.erb
<div data-update-url="<%= note_path(note) %>" class="note" style="margin-left: 10px;">
  <div class="disclose ui-icon ui-icon-minusthick" style="float: left; display: block">+</div>
  <div style="float:left"><%= best_in_place note, :text, :as => :textarea, :display_with => lambda { |v| simple_format(v, {}, wrapper_tag: 'div') } %></div>
  <div style="position: absolute;right: 0px;margin-top: -7px;"><%= link_to 'x', note, method: :delete, remote: true %></div>
  <div class="actions">
    <%= link_to('+', new_note_path, class: 'new-sub-note', style: 'text-decoration: none;', data: {note_id: note.id}) %>
  </div>
  <ol class="sub-notes">
    <%= render 'sub_notes', notes: note.children if note.children.present? %>
  </ol>
</div>

app/views/notes/_sub_notes.html.erb
<% notes.each do |note| %>
    <li>
      <%= render 'sub_note', note: note %>
    </li>
    <%= render 'sub_notes', notes: note.children if note.children.present? %>
<% end %>

app/views/notes/create.js.erb
if(<%= @note.parents.exists? %>){
  $('input[value="<%= params[:authenticity_token] %>').closest('.note').find('.sub-notes').append('<li><%=j render 'sub_note', note: @note %></li>')
} else {
 $('#selectable').append('<%=j render @note %>');
 initnotes();
}
$('input[value="<%= params[:authenticity_token] %>').closest('form').remove();

app/views/notes/destroy.js.erb
$('.note[style*="top: <%= @note.ypos %>px; left: <%= @note.xpos %>px;"]').remove();

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>
<div id="selectable">
<% @notes.roots.each do |note| %>
 <%= render note %>
<% end %>
</div>

app/views/notes/new.html.erb
<%= render 'static_form' %>

app/views/notes/new.js.erb
$('body').append('<%= j render('form') %>');
$('.new_note').draggable({
    stop: function( event, ui ) {
        $(this).find('input[name="note[xpos]"]').val($(this).css('left'));
        $(this).find('input[name="note[ypos]"]').val($(this).css('top'));
    }
});

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<p>
  <strong>Xpos:</strong>
  <%= @note.xpos %>
</p>

<p>
  <strong>Ypos:</strong>
  <%= @note.ypos %>
</p>

<p>
  <strong>Width:</strong>
  <%= @note.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @note.height %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>